# Generated by Django 4.1.4 on 2023-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('meter1', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=50)),
                ('subdescription1', models.TextField(max_length=200)),
                ('meter2', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=50)),
                ('subdescription2', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
                ('subtitle1', models.CharField(max_length=50)),
                ('description1', models.TextField(max_length=200)),
                ('subtitle2', models.CharField(max_length=50)),
                ('description2', models.TextField(max_length=200)),
                ('subtitle3', models.CharField(max_length=50)),
                ('description3', models.TextField(max_length=200)),
                ('subtitle4', models.CharField(max_length=50)),
                ('description4', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(max_length=100)),
                ('percentage', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogLastSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blogtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContactHoverEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=50)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=50)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContactImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLastsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhoneAndEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('PhoneNumberUrl', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phonenumber', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=100)),
                ('companyname', models.TextField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Contacttitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicesBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicesCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicessectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ContentServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingsectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingsectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingsectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingsectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingsectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketingTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaqLastsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaqLeftQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('description1', models.TextField(max_length=600)),
                ('title2', models.CharField(max_length=50)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='FaqTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='FootersectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FootersectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=100)),
                ('subtitle3', models.CharField(max_length=100)),
                ('subtitle4', models.CharField(max_length=100)),
                ('subtitle5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FootersectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=100)),
                ('subtitle3', models.CharField(max_length=100)),
                ('subtitle4', models.CharField(max_length=100)),
                ('subtitle5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FootersectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=100)),
                ('subtitle3', models.CharField(max_length=100)),
                ('subtitle4', models.CharField(max_length=100)),
                ('subtitle5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('PhoneUrl', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicesBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicesCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
                ('title7', models.CharField(max_length=100)),
                ('title8', models.CharField(max_length=100)),
                ('title9', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicessectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Headeritem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=40)),
                ('PhoneNumberUrl', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeletDiscus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homesectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
                ('img', models.ImageField(upload_to='images')),
                ('subtitle1', models.CharField(max_length=50)),
                ('subdescription1', models.TextField(max_length=200)),
                ('subtitle2', models.CharField(max_length=50)),
                ('subdescription2', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homesectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('meter1', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=50)),
                ('subdescription1', models.TextField(max_length=200)),
                ('meter2', models.CharField(max_length=100)),
                ('subtitle2', models.CharField(max_length=50)),
                ('subdescription2', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homesectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homesectionthird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
                ('img', models.ImageField(upload_to='images')),
                ('subtitle1', models.CharField(max_length=50)),
                ('subdescription1', models.TextField(max_length=200)),
                ('subtitle2', models.CharField(max_length=50)),
                ('subdescription2', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homeservicestitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle1', models.CharField(max_length=50)),
                ('description1', models.TextField(max_length=200)),
                ('subtitle2', models.CharField(max_length=50)),
                ('description2', models.TextField(max_length=200)),
                ('subtitle3', models.CharField(max_length=50)),
                ('description3', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlidertitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sliderbg', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Hometitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=20)),
                ('title3', models.CharField(max_length=20)),
                ('description1', models.TextField(max_length=200)),
                ('description2', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
                ('Shortdescription', models.TextField(max_length=200)),
                ('description1', models.TextField(max_length=6000)),
                ('description2', models.TextField(max_length=6000)),
                ('description3', models.TextField(max_length=6000)),
                ('relatedimg1', models.ImageField(upload_to='images')),
                ('relatedimg2', models.ImageField(upload_to='images')),
                ('relatedimg3', models.ImageField(upload_to='images')),
                ('relatedimg4', models.ImageField(upload_to='images')),
                ('relatedimg5', models.ImageField(upload_to='images')),
                ('relatedimg6', models.ImageField(upload_to='images')),
                ('description7', models.TextField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='NavLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PorftolioCategoie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PorftolioCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('seo', 'SEO'), ('GraphiceDesigning', 'GRAPHICSDESIGNING'), ('digitalmarketing', 'digitalmarketing'), ('WebDevelopment', 'WEBDEVELOPMENT'), ('contentwriting', 'contentwriting'), ('videoediting', 'videoEditing')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PorftolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Porftoliotitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyLastsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySectionSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
                ('description3', models.CharField(max_length=600)),
                ('description4', models.CharField(max_length=600)),
                ('description5', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMsectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMsectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMsectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMsectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMsectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesAllIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.ImageField(upload_to='images')),
                ('icon2', models.ImageField(upload_to='images')),
                ('icon3', models.ImageField(upload_to='images')),
                ('icon4', models.ImageField(upload_to='images')),
                ('icon5', models.ImageField(upload_to='images')),
                ('icon6', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicessectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Servicessectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Servicessectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicessectionSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ServicessectionSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Servicessectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ServicessectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicesBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('video', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicesCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('title4', models.CharField(max_length=100)),
                ('title5', models.CharField(max_length=100)),
                ('title6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionsixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionSubfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionSubthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='WebServicessectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.TextField(max_length=600)),
                ('description2', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='WebServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
