# Generated by Django 4.1.4 on 2023-01-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsAllIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.ImageField(upload_to='images')),
                ('icon2', models.ImageField(upload_to='images')),
                ('icon3', models.ImageField(upload_to='images')),
                ('icon4', models.ImageField(upload_to='images')),
                ('icon5', models.ImageField(upload_to='images')),
                ('icon6', models.ImageField(upload_to='images')),
                ('icon7', models.ImageField(upload_to='images')),
                ('icon8', models.ImageField(upload_to='images')),
                ('icon9', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Graphicsfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsSubfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
    ]
