# Generated by Django 4.1.4 on 2023-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_weballicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentWritingAllIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.ImageField(upload_to='images')),
                ('icon2', models.ImageField(upload_to='images')),
                ('icon3', models.ImageField(upload_to='images')),
                ('icon4', models.ImageField(upload_to='images')),
                ('icon5', models.ImageField(upload_to='images')),
                ('icon6', models.ImageField(upload_to='images')),
            ],
        ),
    ]
