# Generated by Django 4.1.4 on 2023-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contentwritingallicons'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentservicescategorie',
            name='title7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contentservicescategorie',
            name='title8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contentservicescategorie',
            name='title9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contentwritingallicons',
            name='icon7',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='contentwritingallicons',
            name='icon8',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='contentwritingallicons',
            name='icon9',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
