# Generated by Django 4.1.4 on 2023-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contentservicessectionfive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEditingAllIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.ImageField(upload_to='images')),
                ('icon2', models.ImageField(upload_to='images')),
                ('icon3', models.ImageField(upload_to='images')),
                ('icon4', models.ImageField(upload_to='images')),
                ('icon5', models.ImageField(upload_to='images')),
                ('icon6', models.ImageField(upload_to='images')),
                ('icon7', models.ImageField(upload_to='images')),
                ('icon8', models.ImageField(upload_to='images')),
                ('icon9', models.ImageField(upload_to='images')),
                ('icon10', models.ImageField(upload_to='images')),
                ('icon11', models.ImageField(upload_to='images')),
                ('icon12', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='videoeditingcategorie',
            name='title10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoeditingcategorie',
            name='title11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoeditingcategorie',
            name='title12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoeditingcategorie',
            name='title7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoeditingcategorie',
            name='title8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoeditingcategorie',
            name='title9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
