# Generated by Django 4.1.4 on 2023-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_videoeditingallicons_videoeditingcategorie_title10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEditingsectionfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingsectionSubfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditingSubSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
    ]
