# Generated by Django 4.1.4 on 2023-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_digitalmarketingallicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSEMSectionFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='SEOSEMSubtFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=600)),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.CharField(max_length=600)),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name='seosemcategorie',
            name='title7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seosemcategorie',
            name='title8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seosemcategorie',
            name='title9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
