# Generated by Django 4.1.4 on 2023-01-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_seosemallicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionLastsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionSectionfifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionSectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionSectionSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionSectionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
                ('description3', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=600)),
                ('description2', models.CharField(max_length=600)),
                ('description3', models.CharField(max_length=600)),
                ('description4', models.CharField(max_length=600)),
                ('description5', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
