# Generated by Django 4.1.4 on 2023-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_privacybg_termsandconditionbg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porftoliocategorie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
