# Generated by Django 4.1.4 on 2023-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_porftoliocategorie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='porftoliocategorie',
            name='visitUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porftoliocategorie',
            name='visititle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
