# Generated by Django 4.1.4 on 2023-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_porftoliocategorie_visiturl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.ImageField(upload_to='images')),
                ('icon2', models.ImageField(upload_to='images')),
                ('icon3', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='HomeIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.ImageField(upload_to='images')),
                ('icon2', models.ImageField(upload_to='images')),
                ('icon3', models.ImageField(upload_to='images')),
                ('icon4', models.ImageField(upload_to='images')),
            ],
        ),
    ]
