# Generated by Django 4.1.4 on 2023-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contacticons_homeicons'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartProjectContactAllDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=100)),
                ('PhoneUrl', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
